# Generated by Django 4.2.6 on 2023-10-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sumary',
            field=models.TextField(),
        ),
    ]
